### ISSUE TITLE
Speed up information

### ISSUE THREAD

**Issue by blondski** [jingyue202205/DSVT-AI-TRT#2]
What is the achieved speed-up with this deployment? Did you run the model without TRT and could show us the results?
Thanks

**Comment by Tigerold** [comment]
The author adapts the way using TensorRT API, of coruse, you need to be similar whit TensorRT. However,this method is not easy to DEBUG.
I used a combination of onnx and TensorRT plugin to achieve this result。I splited the model to sub-model (dynamic-vfe, dsvt_input_layer,dsvt_block,scatter, 3Dbackbone) that running the TenosRT,and python and c++ result are the same.

python version
![1_0](https://github.com/jingyue202205/DSVT-AI-TRT/assets/22309810/75598443-1e92-4ede-bf53-3a2b08f541e4)


c++ version
![1_1](https://github.com/jingyue202205/DSVT-AI-TRT/assets/22309810/b15904a2-1548-4eb5-b4b2-55bb4a4fc0ed)

**Comment by Tigerold** [comment]
Here, many thanks to the author for contributions to projece deployment!!

**Comment by sccdyang** [comment]
> The author adapts the way using TensorRT API, of coruse, you need to be similar whit TensorRT. However,this method is not easy to DEBUG. I used a combination of onnx and TensorRT plugin to achieve this result。I splited the model to sub-model (dynamic-vfe, dsvt_input_layer,dsvt_block,scatter, 3Dbackbone) that running the TenosRT,and python and c++ result are the same.
> 
> python version ![1_0](https://user-images.githubusercontent.com/22309810/279555784-75598443-1e92-4ede-bf53-3a2b08f541e4.png)
> 
> c++ version ![1_1](https://user-images.githubusercontent.com/22309810/279555794-b15904a2-1548-4eb5-b4b2-55bb4a4fc0ed.png)

Have you compared the reasoning results between this project and the PT model to see if they are consistent? Can we open source the corresponding PT model for this project? The results of the current retraining are inconsistent.

**Comment by Tigerold** [comment]
The results are consistent based on python or TensorRT environments. even if there are sight different, but effect is small.

**Comment by sccdyang** [comment]
> The results are consistent based on python or TensorRT environments. even if there are sight different, but effect is small.

Is it your own model?   I mean use jingyue202205/DSVT-AI-TRT/tools/dsvt_cbgs_dyn_pp_centerpoint.yaml to train own pt model,then get the  dsvt-my.wts,then test the dsvt-my.wts as  jingyue202205/DSVT-AI-TRT,finally the results between own pt and  DSVT-AI-TRT of dsvt-my difference is significant。

**Comment by GuoliangPeng** [comment]
> 无论在python还是TensorRT环境下，结果都是一致的，虽然看上去有些不同，但是影响很小。

Hello, thank you for your excellent work. I used DSVT-AI-TRT for deployment testing and found that the results of Python and C++were inconsistent, but I couldn't find the reason. Can you share your complete deployment code? I would like to research it, thank you very much！ gl.peng@outlook.com

**Comment by Tigerold** [comment]
> > 无论在python还是TensorRT环境下，结果都是一致的，虽然看上去有些不同，但是影响很小。
> 
> Hello, thank you for your excellent work. I used DSVT-AI-TRT for deployment testing and found that the results of Python and C++were inconsistent, but I couldn't find the reason. Can you share your complete deployment code? I would like to research it, thank you very much！ [gl.peng@outlook.com](mailto:gl.peng@outlook.com)

You can refer to my repository(https://github.com/LinuxCup/DSVT-AI-TRT) forked from the original.

**Comment by YoushaaMurhij** [comment]
Hello, thank you for your excellent work. I used DSVT-AI-TRT for deployment, too. The TensorRT version skips some objects even if they are close or clearly seen (a lot of lidar points on the object). Even though it manages to detect them the next frame. I tried to increase number of pillars and HM_TOP_K, lower score but nothing changed. Any suggestions or comments why this could happen?

Here is a comparison:

**Torch/Python version:**

<img width="1512" height="877" alt="Image" src="https://github.com/user-attachments/assets/c54bd3bc-0d0b-4132-82ae-a9fb6365f42f" />

**TensorRT/Cpp version:**

<img width="1512" height="876" alt="Image" src="https://github.com/user-attachments/assets/6fc882ac-a557-42e6-9ce8-21e15ba4abd6" />
